[general]
email = ""



[earthengine]
#EARTHENGINE_TOKEN='4/1AX4XfWho968HuPfLIOFyNB0JIQYrJ-L-Fnt-JQNE7z64vrDxkpsSXH0RVjs'

#{"refresh_token": "1//09sD5qI4YIReECgYIARAAGAkSNwF-L9Ir-fXN8MGzLbuOz597wG40sRN_vQDmzPSjioIjmDYraUv60hKA8LkGPHYXjk-qRqhguUI"}

